namespace: divistant
name: integraci
version: 1.0.0
description:
  Ansible collection for managing various tools and services used in IntegraCI projects.
readme: README.md
license_file: LICENSE
repository: https://github.com/integraci-projects/ansible-collection.git
authors:
   - Muhammad Naufal <naufal.khoirul@divistant.com
   - Irkham Hidayat <irkham.hidayat@divistant.com>
dependencies:
   "ansible.utils": "*"
   "ansible.windows": "*"
   "community.windows": "*"
   "chocolatey.chocolatey": "*"
license:
   - GPL-3.0-or-later
tags:
   - collection
   - integraci
