---
- name: Install required package (Linux)
  become: true
  loop:
    - wget
    - unzip
  when: ansible_system == "Linux"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Create directory promtail-custom (Linux)
  when: ansible_system == "Linux"
  file:
    path: /opt/promtail-custom
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy binary promtail-custom (Linux)
  when: ansible_system == "Linux"
  copy:
    src: promtail-custom
    dest: /opt/promtail-custom/promtail-custom
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create data directory for promtail-custom (Linux)
  when: ansible_system == "Linux"
  become: true
  ansible.builtin.file:
    path: /opt/promtail-custom/data
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Install required package (Windows)
  become: true
  loop:
    - nssm
  when: ansible_system == "Win32NT"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: latest


- name: Create Promtail install directory (Windows)
  when: ansible_system == "Win32NT"
  ansible.windows.win_file:
    path: "{{ lookup('env', 'ProgramFiles') }}\\promtail-custom"
    state: directory

- name: Create data directory for promtail-custom (Windows)
  when: ansible_system == "Win32NT"
  ansible.windows.win_file:
    path: "{{ lookup('env', 'ProgramFiles') }}\\promtail-custom\\data"
    state: directory


- name: Copy Promtail custom binary (Windows)
  when: ansible_system == "Win32NT"
  ansible.windows.win_copy:
    src: "{{ role_path }}/files/promtail-custom.exe"
    dest: "{{ lookup('env', 'ProgramFiles') }}\\promtail-custom\\promtail-custom.exe"


- name: Deploy Promtail config file (Windows)
  when: ansible_system == "Win32NT"
  ansible.windows.win_template:
    src: config.yml.j2
    dest: "{{ lookup('env', 'ProgramFiles') }}\\promtail-custom\\config.yml"

- name: Get Program Files path from Windows
  when: ansible_system == "Win32NT"
  ansible.builtin.set_fact:
    programfiles_env: "{{ lookup('env', 'ProgramFiles') }}"

- name: Install Promtail service with NSSM (Windows)
  become: true
  when: ansible_system == "Win32NT"
  community.windows.win_nssm:
    name: promtail-custom
    display_name: Promtail Custom
    application: "{{ programfiles_env }}\\promtail-custom\\promtail-custom.exe"
    arguments: '-config.file "{{ programfiles_env }}\\promtail-custom\\config.yml"'
    app_directory: "{{ programfiles_env }}\\promtail-custom"
    start_mode: auto
    state: started




- name: Install Promtail service config (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.template:
    src: "systemd/promtail-custom.service.j2"
    dest: /usr/lib/systemd/system/promtail-custom.service
    mode: "0644"

- name: Deploy Promtail config file from template
  when: ansible_system == "Linux"
  become: true
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: /opt/promtail-custom/config.yml
    owner: nobody
    group: nogroup
    mode: "0644"
  notify: Restart promtail

- name: Start Promtail service (Linux)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd_service:
    name: promtail-custom
    daemon_reload: true
    enabled: true

- name: Start Promtail service (Windows)
  become: true
  when: ansible_system == "Win32NT"
  ansible.windows.win_service:
    name: promtail-custom
    start_mode: auto


