---
- name: Write Promtail config (Linux)
  become: true
  when: ansible_system == "Linux"
  ansible.builtin.copy:
    content: "{{ promtail_config | ansible.builtin.to_yaml }}"
    dest: /opt/promtail-custom/config.yml
    mode: "0644"
    owner: nobody
    group: nogroup

- name: Ensure Promtail data directory exists
  ansible.windows.win_file:
    path: "%ProgramFiles%\\Promtail Custom\\config.yml"
    state: directory

- name: Write Promtail config (Windows)
  become: true
  when: ansible_system == "Win32NT"
  ansible.windows.win_copy:
    content: "{{ promtail_config | ansible.builtin.to_yaml }}"
    dest: "%ProgramFiles%\\Promtail Custom\\config.yml"
