---
- name: Uninstall custom Promtail service config (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.file:
    path: /usr/lib/systemd/system/promtail-custom.service
    state: absent

- name: Uninstall custom Promtail service config (Windows)
  become: true
  when: ansible_system == "Win32NT"
  community.windows.win_nssm:
    name: promtail-custom
    state: absent

- name: Uninstall custom Promtail folders and binary (Linux)
  become: true
  loop:
    - /opt/promtail-custom
  when: ansible_system == "Linux"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent

- name: Uninstall custom Promtail folders and binary (Windows)
  become: true
  loop:
    - "%ProgramFiles%\\Promtail Custom"
  when: ansible_system == "Win32NT"
  ignore_errors: true
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
