---
- name: Print hosts properties
  ansible.builtin.debug:
    msg:
      - "Architecture: {{ ansible_architecture }}"
      - "System: {{ ansible_system }}"
      - "Distribution: {{ ansible_distribution }}"
      - "Distribution version: {{ ansible_distribution_version }}"
      - "Service manager: {{ ansible_service_mgr | default('unknown') }}"
