---
- name: Install required package (Windows)
  become: true
  loop:
    - nssm
  when: ansible_system == "Win32NT"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: latest

- name: Create folders for custom Promtail (Linux)
  become: true
  loop:
    - /opt/promtail-custom
    - /opt/promtail-custom/data
  when: ansible_system == "Linux"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: nobody
    group: nogroup

- name: Create folders for custom Promtail (Windows)
  become: true
  loop:
    - "%ProgramFiles%\\Promtail Custom"
    - "%ProgramFiles%\\Promtail Custom\\data"
  when: ansible_system == "Win32NT"
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory

- name: Install custom Promtail binary (Linux)
  become: true
  when: ansible_system == "Linux"
  ansible.builtin.copy:
    src: promtail-custom
    dest: /opt/promtail-custom/promtail-custom
    mode: "0755"
    owner: nobody
    group: nogroup

- name: Install custom Promtail binary (Windows)
  become: true
  when: ansible_system == "Win32NT"
  ansible.windows.win_copy:
    src: promtail-custom.exe
    dest: "%ProgramFiles%\\Promtail Custom\\promtail-custom.exe"

- name: Install Promtail service config (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.template:
    src: "systemd/promtail-custom.service.j2"
    dest: /usr/lib/systemd/system/promtail-custom.service
    mode: "0644"

- name: Install Promtail service config (Windows)
  become: true
  when: ansible_system == "Win32NT"
  community.windows.win_nssm:
    name: promtail-custom
    display_name: Promtail Custom
    application: "%ProgramFiles%\\Promtail Custom\\promtail-custom.exe"
    working_directory: "%ProgramFiles%\\Promtail Custom"
    start_mode: auto
    state: present
