---
- name: Add devices to the folder's all devices list
  ansible.builtin.set_fact:
    syncthing_map_folder_device: >-
      {{
        syncthing_map_folder_device
        | default({})
        | combine({
            item.id: {
              'all': syncthing_map_folder_device[item.id].all | default([]) + [
                  inventory_hostname
                ],
              inventory_hostname: syncthing_map_folder_device[item.id][inventory_hostname] | default([]) + [
                  inventory_hostname
                ],
            }
          }, recursive=True, list_merge='prepend_rp')
      }}

- name: Gather partner devices for the folder
  loop: "{{ item.partners | default([]) }}"
  loop_control:
    loop_var: partner
  ansible.builtin.set_fact:
    syncthing_map_folder_device: >-
      {{
        syncthing_map_folder_device
        | default({})
        | combine({
            item.id: {
              inventory_hostname: syncthing_map_folder_device[item.id][inventory_hostname] | default([]) + [
                  partner
                ],
            }
          }, recursive=True, list_merge='prepend_rp')
      }}
