---
- name: Print hosts properties
  ansible.builtin.debug:
    msg:
      - "Architecture: {{ ansible_architecture }}"
      - "System: {{ ansible_system }}"
      - "Distribution: {{ ansible_distribution }}"
      - "Distribution version: {{ ansible_distribution_version }}"
      - "Service manager: {{ ansible_service_mgr | default('unknown') }}"

- name: Gather the package facts
  ansible.builtin.package_facts:

- name: Set Node Exporter architecture
  ansible.builtin.set_fact:
    node_exporter_architecture: "\
      {% if ansible_architecture in ['x86_64', '64-bit'] %}amd64\
      {% elif ansible_architecture in ['i386', 'i686'] %}386\
      {% elif ansible_architecture == 'aarch64' %}arm64\
      {% else %}amd64{% endif %}"

- name: Print Node Exporter architecture
  ansible.builtin.debug:
    msg: "Node Exporter architecture: {{ node_exporter_architecture }}"
