---
- name: Install Node Exporter binary
  become: true
  when: ansible_system == "Linux"
  ansible.builtin.copy:
    src: node_exporter-linux-{{ node_exporter_architecture }}
    dest: /usr/bin/node_exporter
    mode: "0755"

- name: Install Node Exporter service config (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.template:
    src: "systemd/node-exporter.service.j2"
    dest: /usr/lib/systemd/system/node-exporter.service
    mode: "0644"
