- name: Restart Node Exporter service (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd_service:
    name: node-exporter
    state: restarted
    daemon_reload: true
    masked: false
    enabled: true
