---
- name: Uninstall Node Exporter service config (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.file:
    path: /usr/lib/systemd/system/node-exporter.service
    state: absent

- name: Uninstall Node Exporter binary
  become: true
  loop:
    - /usr/bin/node_exporter
  when: ansible_system == "Linux"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
