---
- name: Create folders for Syncthing (Linux)
  become: true
  become_user: "{{ syncthing_user }}"
  loop: "{{ syncthing_folders }}"
  loop_control:
    label: "{{ item.id }}"
  when: ansible_system == "Linux"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    recurse: true

- name: Create folders for Syncthing (Windows)
  become: true
  become_user: "{{ syncthing_user }}"
  loop: "{{ syncthing_folders }}"
  loop_control:
    label: "{{ item.id }}"
  when: ansible_system == "Win32NT"
  ansible.windows.win_file:
    path: "{{ item.path }}"
    state: directory

- name: Check if Syncthing config exists (Linux)
  become: true
  become_user: "{{ syncthing_user }}"
  register: syncthing_linux_conf_file
  when: ansible_system == "Linux"
  ansible.builtin.stat:
    path: "$HOME/.config/syncthing/config.xml"

- name: Check if Syncthing config exists (Windows)
  become: true
  become_user: "{{ syncthing_user }}"
  register: syncthing_win_conf_file
  when: ansible_system == "Win32NT"
  ansible.windows.win_stat:
    path: "$env:LOCALAPPDATA\\Syncthing\\config.xml"

- name: Generate Syncthing config (Linux)
  become: true
  become_user: "{{ syncthing_user }}"
  changed_when: false
  when:
    - ansible_system == "Linux"
    - not syncthing_linux_conf_file.stat.exists
  ansible.builtin.shell:
    cmd: "syncthing generate --no-default-folder --gui-user={{ syncthing_gui_user }} --gui-password={{ syncthing_gui_password }}"

- name: Generate Syncthing config (Windows)
  become: true
  become_user: "{{ syncthing_user }}"
  changed_when: false
  when:
    - ansible_system == "Win32NT"
    - not syncthing_win_conf_file.stat.exists
  ansible.windows.win_shell: |
    $installPath = "$env:LOCALAPPDATA\Programs\Syncthing"
    $configPath = "$env:LOCALAPPDATA\Syncthing"

    New-Item -ItemType Directory -Path $configPath -Force | Out-Null

    & "$installPath\syncthing.exe" generate --no-default-folder --gui-user={{ syncthing_gui_user }} --gui-password={{ syncthing_gui_password }}

- name: Start Syncthing service (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd_service:
    name: "syncthing@{{ syncthing_user }}"
    state: restarted
    daemon_reload: true
    masked: false
    enabled: true

- name: Start Syncthing service (Windows)
  become: true
  when: ansible_system == "Win32NT"
  ansible.windows.win_service:
    name: syncthing
    state: restarted
