---
- name: Perform Syncthing installation tasks
  when: syncthing_state == "install" 
  tags:
    - setup-all
    - setup-syncthing
    - install-all
    - install-syncthing
  block:
    - name: Gather and set facts for Syncthing installation
      ansible.builtin.include_tasks: fact.yaml
    - name: Install Syncthing
      ansible.builtin.include_tasks: install.yaml
    - name: Configure Syncthing
      ansible.builtin.include_tasks: config.yaml

- name: Perform Syncthing start tasks
  when: syncthing_state == "start"
  tags:
    - setup-all
    - setup-syncthing
  block:
    - name: Start Syncthing service
      ansible.builtin.include_tasks: start.yaml

- name: Perform Syncthing restart tasks
  when: syncthing_state == "restart"
  tags:
    - setup-all
    - setup-syncthing
  block:
    - name: Restart Syncthing service
      ansible.builtin.include_tasks: restart.yaml

- name: Perform Syncthing stop tasks
  when: syncthing_state == "stop"
  tags:
    - setup-all
    - setup-syncthing
  block:
    - name: Stop Syncthing service
      ansible.builtin.include_tasks: stop.yaml

- name: Perform Syncthing uninstallation tasks
  when: syncthing_state == "absent"
  tags:
    - setup-all
    - setup-syncthing
  block:
    - name: Uninstall Syncthing
      ansible.builtin.include_tasks: uninstall.yaml
