- name: Start Syncthing service (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.systemd_service:
    name: "syncthing@{{ syncthing_user }}"
    state: restarted
    daemon_reload: true
    masked: false
    enabled: true

- name: Start Syncthing service (Windows)
  become: true
  when: ansible_system == "Win32NT"
  ansible.windows.win_service:
    name: syncthing
    state: restarted
    start_mode: auto
