---
- name: Get all Syncthing@ services
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  shell: systemctl list-units --type=service --no-legend 'syncthing@*.service' | awk '{print $1}'
  register: syncthing_services

- name: Stop each Syncthing@ service
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
    - syncthing_services.stdout_lines | length > 0
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  loop: "{{ syncthing_services.stdout_lines }}"


- name: Stop Syncthing service (Windows)
  become: true
  when: ansible_system == "Win32NT"
  ansible.windows.win_service:
    name: syncthing
    state: stopped

- name: Uninstall Syncthing service config (systemd)
  become: true
  when:
    - ansible_system == "Linux"
    - ansible_service_mgr == "systemd"
  ansible.builtin.file:
    path: /usr/lib/systemd/system/syncthing@.service
    state: absent

- name: Uninstall Syncthing service config (Windows)
  become: true
  when: ansible_system == "Win32NT"
  community.windows.win_nssm:
    name: syncthing
    state: absent

- name: Uninstall Syncthing binary (Linux)
  become: true
  loop:
    - /usr/local/bin/syncthing
    - ~/syncthing.tar.gz
    - ~/syncthing
  when: ansible_system == "Linux"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent

- name: Uninstall Syncthing binary (Windows)
  become: true
  loop:
    - "%LOCALAPPDATA%\\Programs\\Syncthing"
    - "%LOCALAPPDATA%\\Syncthing"
    - "%TEMP%\\syncthing_install"
  when: ansible_system == "Win32NT"
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
